version: "3.7"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.2-community
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes: 
      - /var/sonarqube/config:/opt/sonarqube/conf
      - /var/sonarqube/data:/opt/sonarqube/data
      - /var/sonarqube/log:/opt/sonarqube/log
      - /var/sonarqube/extension:/opt/sonarqube/extension      
